/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.msc.manuels;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.internal.GsonBuildConfig;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.geom.PageSize;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.net.URI;
import java.util.Arrays;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import com.itextpdf.layout.element.Image;
import java.net.MalformedURLException;

/**
 *
 * @author Michael
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final File CONFIG_FILE = new File("./config.json");

    private Config config;
    private File folder;
    private Magick magick;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //pour centrer l'appli au milieu de l'ecran
        initConfig();
        peupleComposant();
        magick = new Magick(config);
    }

    private void initConfig() {
        try {
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            if (!CONFIG_FILE.exists()) {
                CONFIG_FILE.createNewFile();
                config = new Config();
                String res = gson.toJson(config);
                FileUtils.write(CONFIG_FILE, res, "UTF-8");
                JOptionPane.showMessageDialog(this, "Attention il faut remplir le fichie de config (config.json)", "Erreur", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                return;
            }
            String jsonconfig = FileUtils.readFileToString(CONFIG_FILE, "UTF-8");
            config = gson.fromJson(jsonconfig, Config.class);
            if (config.magickCommande.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Attention il faut remplir le fichie de config (config.json)", "Erreur", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void peupleComposant() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel();
        String pageSizes[] = {"A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "DEFAULT", "EXECUTIVE", "LEDGER", "LEGAL", "LETTER", "TABLOID"};
        model.addAll(Arrays.asList(pageSizes));
        model.setSelectedItem("A5");
        this.jComboBoxImg2PdfPageSize.setModel(model);
    }

    private void saveConfig() {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String res = gson.toJson(config);
        try {
            FileUtils.write(CONFIG_FILE, res, "UTF-8");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getFileWithnoExt(File file) {
        int pos = file.getName().lastIndexOf('.');
        return file.getName().substring(0, pos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupImg2Pdf = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelPdf2Imag = new javax.swing.JPanel();
        jButtonConvertPdf2Img = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPdf2imgNbImg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldPdf2Img = new javax.swing.JFormattedTextField();
        jPanelCrop = new javax.swing.JPanel();
        jButtonConvertCrop = new javax.swing.JButton();
        jTextFieldDensite1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelCropNbImg = new javax.swing.JLabel();
        jLabelNbImageCrop = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDensite2 = new javax.swing.JTextField();
        jLabelCropinfoGeometryURL = new javax.swing.JLabel();
        jLabelCropInfos = new javax.swing.JLabel();
        jPanelimg2Pdf = new javax.swing.JPanel();
        jButtonConvertImg2Pdf = new javax.swing.JButton();
        jComboBoxImg2PdfPageSize = new javax.swing.JComboBox<>();
        jLabelImg2PdfBDBelge = new javax.swing.JLabel();
        jRadioButtonStendard = new javax.swing.JRadioButton();
        jRadioButtonOriginal = new javax.swing.JRadioButton();
        jRadioButtonBdBelge = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabelImg2PdfOriginal = new javax.swing.JLabel();
        jLabelImg2Stendard = new javax.swing.JLabel();
        jFormattedTextFieldImg2PdfHeight = new javax.swing.JFormattedTextField();
        jFormattedTextFieldImg2PdfWidth = new javax.swing.JFormattedTextField();
        jLabelImg2PDFNbImg1 = new javax.swing.JLabel();
        jPanelRotate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelRotateURL1 = new javax.swing.JLabel();
        jButtonConvertirRotate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanelConvert = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonConvertireConvert = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanelResize = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabelResizenfoURL1 = new javax.swing.JLabel();
        jButtonConvertirResize = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanelRename = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButtonConvertirRename = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelFolder = new javax.swing.JLabel();
        jButtonOpenFolder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manuels Rapide");
        setResizable(false);

        jTabbedPane2.setEnabled(false);

        jButtonConvertPdf2Img.setText("Convertir");
        jButtonConvertPdf2Img.setEnabled(false);
        jButtonConvertPdf2Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertPdf2ImgActionPerformed(evt);
            }
        });

        jLabel2.setText("Densité");

        jLabel3.setText("Attention traitement long !");

        jLabelPdf2imgNbImg.setText("Nombres d'images:");

        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Attention*");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jFormattedTextFieldPdf2Img.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldPdf2Img.setText("300");
        jFormattedTextFieldPdf2Img.setEnabled(false);

        javax.swing.GroupLayout jPanelPdf2ImagLayout = new javax.swing.GroupLayout(jPanelPdf2Imag);
        jPanelPdf2Imag.setLayout(jPanelPdf2ImagLayout);
        jPanelPdf2ImagLayout.setHorizontalGroup(
            jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPdf2ImagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPdf2ImagLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelPdf2imgNbImg)
                        .addGap(81, 81, 81))
                    .addGroup(jPanelPdf2ImagLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                        .addComponent(jButtonConvertPdf2Img)))
                .addContainerGap())
            .addGroup(jPanelPdf2ImagLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextFieldPdf2Img, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPdf2ImagLayout.setVerticalGroup(
            jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPdf2ImagLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldPdf2Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabelPdf2imgNbImg)
                .addGap(18, 18, 18)
                .addGroup(jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConvertPdf2Img)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pdf2Img", jPanelPdf2Imag);

        jButtonConvertCrop.setText("Convertir");
        jButtonConvertCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertCropActionPerformed(evt);
            }
        });

        jTextFieldDensite1.setText("Auto");
        jTextFieldDensite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDensite1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Crop page 1");

        jLabelCropNbImg.setText("Nombres d'images:");

        jLabel8.setText("Crop page 2");

        jTextFieldDensite2.setText("Auto");

        jLabelCropinfoGeometryURL.setForeground(new java.awt.Color(0, 153, 255));
        jLabelCropinfoGeometryURL.setText("Info sur le template");
        jLabelCropinfoGeometryURL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCropinfoGeometryURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCropinfoGeometryURLMouseClicked(evt);
            }
        });

        jLabelCropInfos.setForeground(new java.awt.Color(51, 153, 255));
        jLabelCropInfos.setText("Infos");
        jLabelCropInfos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCropInfos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCropInfosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCropLayout = new javax.swing.GroupLayout(jPanelCrop);
        jPanelCrop.setLayout(jPanelCropLayout);
        jPanelCropLayout.setHorizontalGroup(
            jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConvertCrop))
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCropLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldDensite1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCropLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldDensite2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCropinfoGeometryURL, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCropInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCropNbImg)
                .addGap(84, 84, 84))
            .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                    .addContainerGap(520, Short.MAX_VALUE)
                    .addComponent(jLabelNbImageCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)))
        );
        jPanelCropLayout.setVerticalGroup(
            jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDensite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCropinfoGeometryURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDensite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCropInfos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabelCropNbImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConvertCrop)
                .addContainerGap())
            .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCropLayout.createSequentialGroup()
                    .addContainerGap(177, Short.MAX_VALUE)
                    .addComponent(jLabelNbImageCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)))
        );

        jTabbedPane2.addTab("Crop", jPanelCrop);

        jButtonConvertImg2Pdf.setText("Convertir");
        jButtonConvertImg2Pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertImg2PdfActionPerformed(evt);
            }
        });

        jLabelImg2PdfBDBelge.setForeground(new java.awt.Color(0, 153, 255));
        jLabelImg2PdfBDBelge.setText("Info sur le template");
        jLabelImg2PdfBDBelge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImg2PdfBDBelge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImg2PdfBDBelgeMouseClicked(evt);
            }
        });

        buttonGroupImg2Pdf.add(jRadioButtonStendard);
        jRadioButtonStendard.setSelected(true);

        buttonGroupImg2Pdf.add(jRadioButtonOriginal);
        jRadioButtonOriginal.setText("Original");

        buttonGroupImg2Pdf.add(jRadioButtonBdBelge);
        jRadioButtonBdBelge.setText("Autre");

        jLabel18.setText("En pixel");

        jLabelImg2PdfOriginal.setForeground(new java.awt.Color(0, 153, 255));
        jLabelImg2PdfOriginal.setText("Info sur le template");
        jLabelImg2PdfOriginal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImg2PdfOriginal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImg2PdfOriginalMouseClicked(evt);
            }
        });

        jLabelImg2Stendard.setForeground(new java.awt.Color(0, 153, 255));
        jLabelImg2Stendard.setText("Info sur le template");
        jLabelImg2Stendard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImg2Stendard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImg2StendardMouseClicked(evt);
            }
        });

        jFormattedTextFieldImg2PdfHeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldImg2PdfHeight.setText("1248");

        jFormattedTextFieldImg2PdfWidth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldImg2PdfWidth.setText("936");

        jLabelImg2PDFNbImg1.setText("Nombres d'images:");

        javax.swing.GroupLayout jPanelimg2PdfLayout = new javax.swing.GroupLayout(jPanelimg2Pdf);
        jPanelimg2Pdf.setLayout(jPanelimg2PdfLayout);
        jPanelimg2PdfLayout.setHorizontalGroup(
            jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConvertImg2Pdf)
                        .addContainerGap())
                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                .addComponent(jRadioButtonOriginal)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonStendard)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxImg2PdfPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonBdBelge)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldImg2PdfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldImg2PdfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelImg2PdfOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelImg2PdfBDBelge, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelImg2Stendard, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(157, 157, 157))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelimg2PdfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImg2PDFNbImg1)
                .addGap(84, 84, 84))
        );
        jPanelimg2PdfLayout.setVerticalGroup(
            jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelimg2PdfLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxImg2PdfPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonStendard)
                    .addComponent(jLabelImg2Stendard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOriginal)
                    .addComponent(jLabelImg2PdfOriginal))
                .addGap(18, 18, 18)
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBdBelge)
                    .addComponent(jLabel18)
                    .addComponent(jLabelImg2PdfBDBelge)
                    .addComponent(jFormattedTextFieldImg2PdfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldImg2PdfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabelImg2PDFNbImg1)
                .addGap(18, 18, 18)
                .addComponent(jButtonConvertImg2Pdf)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Img2Pdf", jPanelimg2Pdf);

        jLabel11.setText("Rotation");

        jTextField1.setText("90");

        jLabelRotateURL1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelRotateURL1.setText("Info sur le template");
        jLabelRotateURL1.setToolTipText("<html>\nMettre (en degrés) la rotation.<br>\nPeux etre négatif<br>\n<br>\nExemple: 90 ou -90\n</html>");
        jLabelRotateURL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonConvertirRotate.setText("Convertir");

        jLabel12.setText("Nombres d'images:");

        javax.swing.GroupLayout jPanelRotateLayout = new javax.swing.GroupLayout(jPanelRotate);
        jPanelRotate.setLayout(jPanelRotateLayout);
        jPanelRotateLayout.setHorizontalGroup(
            jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRotateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRotateLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelRotateURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 219, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRotateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConvertirRotate)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRotateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(84, 84, 84))
        );
        jPanelRotateLayout.setVerticalGroup(
            jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRotateLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRotateURL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConvertirRotate)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Rotate", jPanelRotate);

        jLabel13.setText("Quel extention convertir ?");

        jTextField2.setText(".png");

        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("Astuces");
        jLabel14.setToolTipText("La sortie serra toujours en .jpg");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonConvertireConvert.setText("Convertir");

        jLabel15.setText("Nombres d'images:");

        javax.swing.GroupLayout jPanelConvertLayout = new javax.swing.GroupLayout(jPanelConvert);
        jPanelConvert.setLayout(jPanelConvertLayout);
        jPanelConvertLayout.setHorizontalGroup(
            jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConvertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConvertLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel14)
                        .addContainerGap(231, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                                .addComponent(jButtonConvertireConvert)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(84, 84, 84))))))
        );
        jPanelConvertLayout.setVerticalGroup(
            jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConvertLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConvertireConvert)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Convert", jPanelConvert);

        jLabel16.setText("Nouvelle taille:");

        jTextField3.setText("50%");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabelResizenfoURL1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelResizenfoURL1.setText("Info sur le template");
        jLabelResizenfoURL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelResizenfoURL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResizenfoURL1MouseClicked(evt);
            }
        });

        jButtonConvertirResize.setText("Convertir");

        jLabel17.setText("Nombres d'images:");

        javax.swing.GroupLayout jPanelResizeLayout = new javax.swing.GroupLayout(jPanelResize);
        jPanelResize.setLayout(jPanelResizeLayout);
        jPanelResizeLayout.setHorizontalGroup(
            jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResizeLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelResizenfoURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResizeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResizeLayout.createSequentialGroup()
                                .addComponent(jButtonConvertirResize)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResizeLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(85, 85, 85))))))
        );
        jPanelResizeLayout.setVerticalGroup(
            jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResizeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResizenfoURL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(11, 11, 11)
                .addComponent(jButtonConvertirResize)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Resize", jPanelResize);

        jScrollPane2.setViewportView(jList2);

        jButton1.setText("No place");
        jButton1.setToolTipText("Permet de placer une ligne directement a la bonne place.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonConvertirRename.setText("Convertir");

        jButton4.setText("Up");

        jButton5.setText("Down");

        jButton8.setText("Suppr");

        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Astuces");
        jLabel10.setToolTipText("<html>\nOn peux appyer sur les fleches haut/bas pour monter/decendre un fichier<br>\n<br>\nOn peux appyer sur suppr pour supprimer une ligne\n</html>");

        javax.swing.GroupLayout jPanelRenameLayout = new javax.swing.GroupLayout(jPanelRename);
        jPanelRename.setLayout(jPanelRenameLayout);
        jPanelRenameLayout.setHorizontalGroup(
            jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRenameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConvertirRename, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenameLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(83, 83, 83)))
                .addContainerGap())
        );
        jPanelRenameLayout.setVerticalGroup(
            jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenameLayout.createSequentialGroup()
                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelRenameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConvertirRename)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Rename", jPanelRename);

        jLabelFolder.setText("Repertoire");

        jButtonOpenFolder.setText("Ouvrir");
        jButtonOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpenFolder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFolder)
                    .addComponent(jButtonOpenFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDensite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDensite1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDensite1ActionPerformed

    private void jLabelCropinfoGeometryURLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCropinfoGeometryURLMouseClicked

        String url = "https://imagemagick.org/script/command-line-processing.php#geometry";
        openURL(url);

    }//GEN-LAST:event_jLabelCropinfoGeometryURLMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabelResizenfoURL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResizenfoURL1MouseClicked

        String url = "https://imagemagick.org/script/command-line-processing.php#geometry";
        openURL(url);
    }//GEN-LAST:event_jLabelResizenfoURL1MouseClicked

    private void jLabelImg2PdfBDBelgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImg2PdfBDBelgeMouseClicked
        JOptionPane.showMessageDialog(this, "la taille proposé de base (936x1248) c'est la taille 24cmx32cm soit le format d'une BD (belge)\nCela permet de forcer une taille si l'on ne veux pas de la taille original\nSi l'un des nom d'une image contient \"paysage\" (exemple: 01-paysage.jpg) elle serra au format paysage dans le rendu du PDF final", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelImg2PdfBDBelgeMouseClicked

    private void jButtonConvertPdf2ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertPdf2ImgActionPerformed
        File pdfs[] = getFiles(folder, false, ".pdf");
        if (pdfs.length == 0) {
            JOptionPane.showMessageDialog(this, "Pas de pdf trouver dans le repertoire choisi", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        File pdf = pdfs[0];

        try {
            magick.launchPdf2Img(pdf, jFormattedTextFieldPdf2Img.getText());
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        new File(folder, "originals").mkdirs();
        File originalPdf = new File(folder, "originals/" + pdf.getName());
        try {
            FileUtils.moveFile(pdf, originalPdf);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        File jpgs[] = getFiles(folder, false, ".jpg");
        jLabelPdf2imgNbImg.setText("Nombres d'images: " + jpgs.length);
    }//GEN-LAST:event_jButtonConvertPdf2ImgActionPerformed

    private void jButtonOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFolderActionPerformed
        JFileChooser fc = new JFileChooser(config.lastFolder);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fc.showDialog(this, "Ouvrir");
        if (res == JFileChooser.APPROVE_OPTION) {
            folder = fc.getSelectedFile();
            jLabelFolder.setText("Répertoire: " + folder.getAbsolutePath());
            jTabbedPane2.setEnabled(true);
            jButtonConvertPdf2Img.setEnabled(true);
            jFormattedTextFieldPdf2Img.setEnabled(true);
            config.lastFolder = folder.getAbsolutePath();
            saveConfig();
        }
    }//GEN-LAST:event_jButtonOpenFolderActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JOptionPane.showMessageDialog(this, "Plus la densité est grande plus la taille du fichier serra grand et lourd.\n\n300 est un tres bon compromis entre qualité / poids / taille", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabelCropInfosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCropInfosMouseClicked
        JOptionPane.showMessageDialog(this, "En Mode Auto, ca coupe au milieu de l'image.\nSinon il faut mettre une largeure x hauteur (voir \"info sur le templates (geometry) \")\nIl vaut mieux laisser en Auto !", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelCropInfosMouseClicked

    private void jButtonConvertCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertCropActionPerformed
        new File(folder, "rendu").mkdirs();
        File[] files = getFiles(folder, false, ".jpg");
        int i = 0;
        for (File file : files) {

            try {
                BufferedImage img = ImageIO.read(file);

                int h = img.getHeight();
                int w = img.getWidth();

                String crop1 = w / 2 + "x" + h + "-0-0";
                String crop2 = w / 2 + "x" + h + "+" + w / 2 + "-0";

                magick.laumchCropMagik(file, crop1, 1);
                magick.laumchCropMagik(file, crop2, 2);

                i += 2;
                jLabelCropNbImg.setText("Nombres d'images: " + i + "/" + (files.length * 2));
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonConvertCropActionPerformed

    private void jLabelImg2PdfOriginalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImg2PdfOriginalMouseClicked
        JOptionPane.showMessageDialog(this, "Mets la taille original des images dans le PDF (faites un resize avant !)\nPratique quand les formats ne sont pas standards\nSi l'un des nom d'une image contient \"paysage\" (exemple: 01-paysage.jpg) elle serra au format paysage dans le rendu du PDF final", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelImg2PdfOriginalMouseClicked

    private void jButtonConvertImg2PdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertImg2PdfActionPerformed
        File files[] = getFiles(folder, true, ".jpg");
        PageSize pg = null;
        try {
            if (jRadioButtonOriginal.isSelected()) {
                Image image = new Image(ImageDataFactory.create(files[0].getAbsolutePath()));
                pg = new PageSize(image.getImageWidth() / 4, image.getImageHeight() / 4);
            } else if (jRadioButtonStendard.isSelected()) {
                String resStr = jComboBoxImg2PdfPageSize.getSelectedItem().toString();
                Field f = PageSize.class.getField(resStr);
                pg = (PageSize) f.get(null);
            } else {
                pg = new PageSize(Float.parseFloat(jFormattedTextFieldImg2PdfWidth.getText()), Float.parseFloat(jFormattedTextFieldImg2PdfHeight.getText()));
            }
            magick.launchImg2Pdf(files, pg);
            jLabelImg2PDFNbImg1.setText("Nombres d'images: "+files.length);
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConvertImg2PdfActionPerformed

    private void jLabelImg2StendardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImg2StendardMouseClicked
        JOptionPane.showMessageDialog(this, "Si l'un des nom d'une image contient \"paysage\" (exemple: 01-paysage.jpg) elle serra au format paysage dans le rendu du PDF final", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelImg2StendardMouseClicked

    private void openURL(String url) {
        Desktop desktop = java.awt.Desktop.getDesktop();
        try {
            desktop.browse(new URI(url));
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private File[] getFiles(File folder, boolean inRendu, String ext) {
        File files[] = null;
        if (inRendu) {
            File newFolder = new File(folder, "rendu");
            newFolder.mkdirs(); // au cas ou
            files = newFolder.listFiles((File pathname) -> pathname.getName().endsWith(ext));
        } else {
            files = folder.listFiles((File pathname) -> pathname.getName().endsWith(ext));
        }
        Arrays.sort(files, Comparator.comparing(File::getName));
        return files;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupImg2Pdf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonConvertCrop;
    private javax.swing.JButton jButtonConvertImg2Pdf;
    private javax.swing.JButton jButtonConvertPdf2Img;
    private javax.swing.JButton jButtonConvertirRename;
    private javax.swing.JButton jButtonConvertirResize;
    private javax.swing.JButton jButtonConvertirRotate;
    private javax.swing.JButton jButtonConvertireConvert;
    private javax.swing.JButton jButtonOpenFolder;
    private javax.swing.JComboBox<String> jComboBoxImg2PdfPageSize;
    private javax.swing.JFormattedTextField jFormattedTextFieldImg2PdfHeight;
    private javax.swing.JFormattedTextField jFormattedTextFieldImg2PdfWidth;
    private javax.swing.JFormattedTextField jFormattedTextFieldPdf2Img;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCropInfos;
    private javax.swing.JLabel jLabelCropNbImg;
    private javax.swing.JLabel jLabelCropinfoGeometryURL;
    private javax.swing.JLabel jLabelFolder;
    private javax.swing.JLabel jLabelImg2PDFNbImg1;
    private javax.swing.JLabel jLabelImg2PdfBDBelge;
    private javax.swing.JLabel jLabelImg2PdfOriginal;
    private javax.swing.JLabel jLabelImg2Stendard;
    private javax.swing.JLabel jLabelNbImageCrop;
    private javax.swing.JLabel jLabelPdf2imgNbImg;
    private javax.swing.JLabel jLabelResizenfoURL1;
    private javax.swing.JLabel jLabelRotateURL1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanelConvert;
    private javax.swing.JPanel jPanelCrop;
    private javax.swing.JPanel jPanelPdf2Imag;
    private javax.swing.JPanel jPanelRename;
    private javax.swing.JPanel jPanelResize;
    private javax.swing.JPanel jPanelRotate;
    private javax.swing.JPanel jPanelimg2Pdf;
    private javax.swing.JRadioButton jRadioButtonBdBelge;
    private javax.swing.JRadioButton jRadioButtonOriginal;
    private javax.swing.JRadioButton jRadioButtonStendard;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldDensite1;
    private javax.swing.JTextField jTextFieldDensite2;
    // End of variables declaration//GEN-END:variables
}
