/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.msc.manuels;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.geom.PageSize;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.net.URI;
import java.util.Arrays;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;
import com.itextpdf.layout.element.Image;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Michael
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final File CONFIG_FILE = new File("./config.json");

    private Config config;
    private File folder;
    private Magick magick;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //pour centrer l'appli au milieu de l'ecran
        initConfig();
        peupleComposant();
        magick = new Magick(config);
    }

    private void initConfig() {
        try {
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            if (!CONFIG_FILE.exists()) {
                CONFIG_FILE.createNewFile();
                config = new Config();
                String res = gson.toJson(config);
                FileUtils.write(CONFIG_FILE, res, "UTF-8");
                JOptionPane.showMessageDialog(this, "Attention il faut remplir le fichie de config (config.json)", "Erreur", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                return;
            }
            String jsonconfig = FileUtils.readFileToString(CONFIG_FILE, "UTF-8");
            config = gson.fromJson(jsonconfig, Config.class);
            if (config.magickCommande.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Attention il faut remplir le fichie de config (config.json)", "Erreur", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void peupleComposant() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel();
        String pageSizes[] = {"A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "DEFAULT", "EXECUTIVE", "LEDGER", "LEGAL", "LETTER", "TABLOID"};
        model.addAll(Arrays.asList(pageSizes));
        model.setSelectedItem("A5");
        this.jComboBoxImg2PdfPageSize.setModel(model);

        this.jListCropAGarder.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        this.jListCropAExclure.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    }

    private void saveConfig() {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String res = gson.toJson(config);
        try {
            FileUtils.write(CONFIG_FILE, res, "UTF-8");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void moveFileToFolder(File original, String folderDest) {
        new File(folder, folderDest).mkdirs();
        File originalPdf = new File(folder, folderDest + "/" + original.getName());
        try {
            FileUtils.moveFile(original, originalPdf);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupImg2Pdf = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelPdf2Imag = new javax.swing.JPanel();
        jButtonConvertPdf2Img = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPdf2imgNbImg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldPdf2Img = new javax.swing.JFormattedTextField();
        jPanelCrop = new javax.swing.JPanel();
        jButtonConvertCrop = new javax.swing.JButton();
        jTextFieldCrop1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelCropNbImg = new javax.swing.JLabel();
        jLabelNbImageCrop = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCrop2 = new javax.swing.JTextField();
        jLabelCropinfoGeometryURL = new javax.swing.JLabel();
        jLabelCropInfos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCropAGarder = new javax.swing.JList<>();
        jButtonCropLister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCropAExclure = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButtonCropToExclude = new javax.swing.JButton();
        jButtonCropToInclude = new javax.swing.JButton();
        jLabelCropInfosList = new javax.swing.JLabel();
        jPanelimg2Pdf = new javax.swing.JPanel();
        jButtonConvertImg2Pdf = new javax.swing.JButton();
        jComboBoxImg2PdfPageSize = new javax.swing.JComboBox<>();
        jLabelImg2PdfBDBelge = new javax.swing.JLabel();
        jRadioButtonStendard = new javax.swing.JRadioButton();
        jRadioButtonOriginal = new javax.swing.JRadioButton();
        jRadioButtonBdBelge = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabelImg2PdfOriginal = new javax.swing.JLabel();
        jLabelImg2Stendard = new javax.swing.JLabel();
        jFormattedTextFieldImg2PdfHeight = new javax.swing.JFormattedTextField();
        jFormattedTextFieldImg2PdfWidth = new javax.swing.JFormattedTextField();
        jLabelImg2PDFNbImg1 = new javax.swing.JLabel();
        jPanelRotate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRotate = new javax.swing.JTextField();
        jLabelRotateURL1 = new javax.swing.JLabel();
        jButtonConvertirRotate = new javax.swing.JButton();
        jLabel1RotateNbImg = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanelConvert = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldConvertExt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonConvertireConvert = new javax.swing.JButton();
        jLabelConvertNbImg = new javax.swing.JLabel();
        jPanelResize = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldResizeText = new javax.swing.JTextField();
        jLabelResizenfoURL1 = new javax.swing.JLabel();
        jButtonConvertirResize = new javax.swing.JButton();
        jLabel1ConvertNbImage = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelRename = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRenameList = new javax.swing.JList<>();
        jButtonConvertirRename = new javax.swing.JButton();
        jButtonRenameUp = new javax.swing.JButton();
        jButtonRenameDown = new javax.swing.JButton();
        jButtonRenameSuppr = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonRenameReset = new javax.swing.JButton();
        jLabelRenameNbImage1 = new javax.swing.JLabel();
        jButtonRenamePgUp = new javax.swing.JButton();
        jButtonRenamePgDown = new javax.swing.JButton();
        jLabelFolder = new javax.swing.JLabel();
        jButtonOpenFolder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manuels Rapide");

        jTabbedPane2.setEnabled(false);

        jButtonConvertPdf2Img.setText("Convertir");
        jButtonConvertPdf2Img.setEnabled(false);
        jButtonConvertPdf2Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertPdf2ImgActionPerformed(evt);
            }
        });

        jLabel2.setText("Densité");

        jLabel3.setText("Attention traitement long !");

        jLabelPdf2imgNbImg.setText("Nombres d'images:");

        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Infos");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jFormattedTextFieldPdf2Img.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldPdf2Img.setText("300");
        jFormattedTextFieldPdf2Img.setEnabled(false);

        javax.swing.GroupLayout jPanelPdf2ImagLayout = new javax.swing.GroupLayout(jPanelPdf2Imag);
        jPanelPdf2Imag.setLayout(jPanelPdf2ImagLayout);
        jPanelPdf2ImagLayout.setHorizontalGroup(
            jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPdf2ImagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPdf2ImagLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelPdf2imgNbImg)
                        .addGap(81, 81, 81))
                    .addGroup(jPanelPdf2ImagLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addComponent(jButtonConvertPdf2Img)))
                .addContainerGap())
            .addGroup(jPanelPdf2ImagLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextFieldPdf2Img, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPdf2ImagLayout.setVerticalGroup(
            jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPdf2ImagLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldPdf2Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jLabelPdf2imgNbImg)
                .addGap(18, 18, 18)
                .addGroup(jPanelPdf2ImagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConvertPdf2Img)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pdf2Img", jPanelPdf2Imag);

        jButtonConvertCrop.setText("Convertir");
        jButtonConvertCrop.setEnabled(false);
        jButtonConvertCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertCropActionPerformed(evt);
            }
        });

        jTextFieldCrop1.setText("Auto");

        jLabel5.setText("Crop page 1");

        jLabelCropNbImg.setText("Nombres d'images:");

        jLabel8.setText("Crop page 2");

        jTextFieldCrop2.setText("Auto");

        jLabelCropinfoGeometryURL.setForeground(new java.awt.Color(0, 153, 255));
        jLabelCropinfoGeometryURL.setText("Infos");
        jLabelCropinfoGeometryURL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCropinfoGeometryURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCropinfoGeometryURLMouseClicked(evt);
            }
        });

        jLabelCropInfos.setForeground(new java.awt.Color(0, 153, 255));
        jLabelCropInfos.setText("Infos");
        jLabelCropInfos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCropInfos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCropInfosMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jListCropAGarder);

        jButtonCropLister.setText("Lister");
        jButtonCropLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCropListerActionPerformed(evt);
            }
        });

        jLabel1.setText("A garder");

        jScrollPane3.setViewportView(jListCropAExclure);

        jLabel4.setText("A exclure");

        jButtonCropToExclude.setText(">");
        jButtonCropToExclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCropToExcludeActionPerformed(evt);
            }
        });

        jButtonCropToInclude.setText("<");
        jButtonCropToInclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCropToIncludeActionPerformed(evt);
            }
        });

        jLabelCropInfosList.setForeground(new java.awt.Color(0, 153, 255));
        jLabelCropInfosList.setText("Infos");
        jLabelCropInfosList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCropInfosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCropInfosListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCropLayout = new javax.swing.GroupLayout(jPanelCrop);
        jPanelCrop.setLayout(jPanelCropLayout);
        jPanelCropLayout.setHorizontalGroup(
            jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57)
                        .addComponent(jTextFieldCrop1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57)
                        .addComponent(jTextFieldCrop2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4))
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCropToInclude)
                            .addComponent(jButtonCropToExclude, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConvertCrop, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                                .addComponent(jLabelCropNbImg)
                                .addGap(78, 78, 78))))
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCropinfoGeometryURL, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCropInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCropLister)
                            .addComponent(jLabelCropInfosList, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                    .addContainerGap(594, Short.MAX_VALUE)
                    .addComponent(jLabelNbImageCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)))
        );
        jPanelCropLayout.setVerticalGroup(
            jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCrop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCropinfoGeometryURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCrop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCropInfos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCropLayout.createSequentialGroup()
                                .addComponent(jButtonCropLister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCropInfosList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCropNbImg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConvertCrop)
                                .addContainerGap())
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanelCropLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButtonCropToExclude)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCropToInclude)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCropLayout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(jLabelNbImageCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(67, 67, 67)))
        );

        jTabbedPane2.addTab("Crop", jPanelCrop);

        jButtonConvertImg2Pdf.setText("Convertir");
        jButtonConvertImg2Pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertImg2PdfActionPerformed(evt);
            }
        });

        jLabelImg2PdfBDBelge.setForeground(new java.awt.Color(0, 153, 255));
        jLabelImg2PdfBDBelge.setText("Infos");
        jLabelImg2PdfBDBelge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImg2PdfBDBelge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImg2PdfBDBelgeMouseClicked(evt);
            }
        });

        buttonGroupImg2Pdf.add(jRadioButtonStendard);
        jRadioButtonStendard.setSelected(true);

        buttonGroupImg2Pdf.add(jRadioButtonOriginal);
        jRadioButtonOriginal.setText("Original");

        buttonGroupImg2Pdf.add(jRadioButtonBdBelge);
        jRadioButtonBdBelge.setText("Autre");

        jLabel18.setText("En pixel");

        jLabelImg2PdfOriginal.setForeground(new java.awt.Color(0, 153, 255));
        jLabelImg2PdfOriginal.setText("Infos");
        jLabelImg2PdfOriginal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImg2PdfOriginal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImg2PdfOriginalMouseClicked(evt);
            }
        });

        jLabelImg2Stendard.setForeground(new java.awt.Color(0, 153, 255));
        jLabelImg2Stendard.setText("Infos");
        jLabelImg2Stendard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImg2Stendard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImg2StendardMouseClicked(evt);
            }
        });

        jFormattedTextFieldImg2PdfHeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldImg2PdfHeight.setText("1248");

        jFormattedTextFieldImg2PdfWidth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldImg2PdfWidth.setText("936");

        jLabelImg2PDFNbImg1.setText("Nombres d'images:");

        javax.swing.GroupLayout jPanelimg2PdfLayout = new javax.swing.GroupLayout(jPanelimg2Pdf);
        jPanelimg2Pdf.setLayout(jPanelimg2PdfLayout);
        jPanelimg2PdfLayout.setHorizontalGroup(
            jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConvertImg2Pdf)
                        .addContainerGap())
                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                .addComponent(jRadioButtonOriginal)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonStendard)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxImg2PdfPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelimg2PdfLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonBdBelge)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldImg2PdfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldImg2PdfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelImg2PdfOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelImg2PdfBDBelge, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelImg2Stendard, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(157, 157, 157))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelimg2PdfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImg2PDFNbImg1)
                .addGap(84, 84, 84))
        );
        jPanelimg2PdfLayout.setVerticalGroup(
            jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelimg2PdfLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonStendard)
                    .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxImg2PdfPageSize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelImg2Stendard)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOriginal)
                    .addComponent(jLabelImg2PdfOriginal))
                .addGap(18, 18, 18)
                .addGroup(jPanelimg2PdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBdBelge)
                    .addComponent(jLabel18)
                    .addComponent(jLabelImg2PdfBDBelge)
                    .addComponent(jFormattedTextFieldImg2PdfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldImg2PdfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabelImg2PDFNbImg1)
                .addGap(18, 18, 18)
                .addComponent(jButtonConvertImg2Pdf)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Img2Pdf", jPanelimg2Pdf);

        jLabel11.setText("Rotation");

        jTextFieldRotate.setText("90");

        jLabelRotateURL1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelRotateURL1.setText("Infos");
        jLabelRotateURL1.setToolTipText("");
        jLabelRotateURL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRotateURL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRotateURL1MouseClicked(evt);
            }
        });

        jButtonConvertirRotate.setText("Convertir");
        jButtonConvertirRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirRotateActionPerformed(evt);
            }
        });

        jLabel1RotateNbImg.setText("Nombres d'images:");

        jCheckBox2.setText("Ecraser les fichiers originaux ?");

        javax.swing.GroupLayout jPanelRotateLayout = new javax.swing.GroupLayout(jPanelRotate);
        jPanelRotate.setLayout(jPanelRotateLayout);
        jPanelRotateLayout.setHorizontalGroup(
            jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRotateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1RotateNbImg)
                .addGap(84, 84, 84))
            .addGroup(jPanelRotateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRotateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConvertirRotate))
                    .addGroup(jPanelRotateLayout.createSequentialGroup()
                        .addGroup(jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRotateLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabelRotateURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox2))
                        .addGap(0, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRotateLayout.setVerticalGroup(
            jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRotateLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldRotate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRotateURL1))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel1RotateNbImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConvertirRotate)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Rotate", jPanelRotate);

        jLabel13.setText("Quel extention convertir ?");

        jTextFieldConvertExt.setText(".png");

        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("Infos");
        jLabel14.setToolTipText("");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jButtonConvertireConvert.setText("Convertir");
        jButtonConvertireConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertireConvertActionPerformed(evt);
            }
        });

        jLabelConvertNbImg.setText("Nombres d'images:");

        javax.swing.GroupLayout jPanelConvertLayout = new javax.swing.GroupLayout(jPanelConvert);
        jPanelConvert.setLayout(jPanelConvertLayout);
        jPanelConvertLayout.setHorizontalGroup(
            jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConvertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConvertLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldConvertExt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel14)
                        .addContainerGap(286, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                                .addComponent(jButtonConvertireConvert)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                                .addComponent(jLabelConvertNbImg)
                                .addGap(84, 84, 84))))))
        );
        jPanelConvertLayout.setVerticalGroup(
            jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConvertLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldConvertExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jLabelConvertNbImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConvertireConvert)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Convert", jPanelConvert);

        jLabel16.setText("Nouvelle taille:");

        jTextFieldResizeText.setText("50%");

        jLabelResizenfoURL1.setForeground(new java.awt.Color(0, 153, 255));
        jLabelResizenfoURL1.setText("Infos");
        jLabelResizenfoURL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelResizenfoURL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResizenfoURL1MouseClicked(evt);
            }
        });

        jButtonConvertirResize.setText("Convertir");
        jButtonConvertirResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirResizeActionPerformed(evt);
            }
        });

        jLabel1ConvertNbImage.setText("Nombres d'images:");

        jCheckBox1.setText("Ecraser les fichiers originaux ?");

        javax.swing.GroupLayout jPanelResizeLayout = new javax.swing.GroupLayout(jPanelResize);
        jPanelResize.setLayout(jPanelResizeLayout);
        jPanelResizeLayout.setHorizontalGroup(
            jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResizeLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldResizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelResizenfoURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(216, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResizeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResizeLayout.createSequentialGroup()
                                .addComponent(jButtonConvertirResize)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResizeLayout.createSequentialGroup()
                                .addComponent(jLabel1ConvertNbImage)
                                .addGap(85, 85, 85))))
                    .addGroup(jPanelResizeLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelResizeLayout.setVerticalGroup(
            jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResizeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldResizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResizenfoURL1))
                .addGap(29, 29, 29)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel1ConvertNbImage)
                .addGap(11, 11, 11)
                .addComponent(jButtonConvertirResize)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Resize", jPanelResize);

        jListRenameList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListRenameListKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jListRenameList);

        jButtonConvertirRename.setText("Convertir");
        jButtonConvertirRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirRenameActionPerformed(evt);
            }
        });

        jButtonRenameUp.setText("Up");
        jButtonRenameUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameUpActionPerformed(evt);
            }
        });

        jButtonRenameDown.setText("Down");
        jButtonRenameDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameDownActionPerformed(evt);
            }
        });

        jButtonRenameSuppr.setText("Suppr");
        jButtonRenameSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameSupprActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Infos");
        jLabel10.setToolTipText("On peux appyer sur les fleches haut/bas pour monter/decendre un fichier\\n\nOn peux appuyer sur Page up/pagedown pour aller de 10 en 10\\n\nOn peux appyer sur suppr pour supprimer une ligne\n");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jButtonRenameReset.setText("Reset");
        jButtonRenameReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameResetActionPerformed(evt);
            }
        });

        jLabelRenameNbImage1.setText("Nombres d'images:");

        jButtonRenamePgUp.setText("Pg Up");
        jButtonRenamePgUp.setToolTipText("Remonte de 10");
        jButtonRenamePgUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenamePgUpActionPerformed(evt);
            }
        });

        jButtonRenamePgDown.setText("Pg Down");
        jButtonRenamePgDown.setToolTipText("Descends de 10");
        jButtonRenamePgDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenamePgDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRenameLayout = new javax.swing.GroupLayout(jPanelRename);
        jPanelRename.setLayout(jPanelRenameLayout);
        jPanelRenameLayout.setHorizontalGroup(
            jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRenameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRenameLayout.createSequentialGroup()
                        .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRenameReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonConvertirRename, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanelRenameLayout.createSequentialGroup()
                                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonRenameSuppr, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jButtonRenameUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRenamePgUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRenameDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelRenameLayout.createSequentialGroup()
                        .addComponent(jButtonRenamePgDown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jLabelRenameNbImage1)
                        .addGap(82, 82, 82))))
        );
        jPanelRenameLayout.setVerticalGroup(
            jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenameLayout.createSequentialGroup()
                .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelRenameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRenameSuppr)
                            .addComponent(jLabel10))
                        .addGap(7, 7, 7)
                        .addComponent(jButtonRenameReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonRenameUp)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRenameDown)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRenamePgUp)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRenameNbImage1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRenamePgDown, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConvertirRename)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Rename", jPanelRename);

        jLabelFolder.setText("Repertoire");

        jButtonOpenFolder.setText("Ouvrir");
        jButtonOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpenFolder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFolder)
                    .addComponent(jButtonOpenFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFolderActionPerformed
        JFileChooser fc = new JFileChooser(config.lastFolder);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fc.showDialog(this, "Ouvrir");
        if (res == JFileChooser.APPROVE_OPTION) {
            folder = fc.getSelectedFile();
            jLabelFolder.setText("Répertoire: " + folder.getAbsolutePath());
            jTabbedPane2.setEnabled(true);
            jButtonConvertPdf2Img.setEnabled(true);
            jFormattedTextFieldPdf2Img.setEnabled(true);
            config.lastFolder = folder.getAbsolutePath();
            saveConfig();
        }
    }//GEN-LAST:event_jButtonOpenFolderActionPerformed

    private void jButtonRenamePgDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenamePgDownActionPerformed
        java.awt.event.KeyEvent ke = new java.awt.event.KeyEvent(this, 0, 0, 0, KeyEvent.VK_PAGE_DOWN, 'd');
        jListRenameListKeyPressed(ke);
    }//GEN-LAST:event_jButtonRenamePgDownActionPerformed

    private void jButtonRenamePgUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenamePgUpActionPerformed
        java.awt.event.KeyEvent ke = new java.awt.event.KeyEvent(this, 0, 0, 0, KeyEvent.VK_PAGE_UP, 'u');
        jListRenameListKeyPressed(ke);
    }//GEN-LAST:event_jButtonRenamePgUpActionPerformed

    private void jButtonRenameResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameResetActionPerformed
        File files[] = getFiles(folder, null);
        DefaultListModel<String> model = new DefaultListModel<>();
        for (File file : files) {
            model.addElement(file.getName());
        }
        jListRenameList.setModel(model);
        resetList = true;
    }//GEN-LAST:event_jButtonRenameResetActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        JOptionPane.showMessageDialog(this, "Permet de renommer les fichier en 00.jpg 01.jpg etc... dans l'ordre de la liste.\nC'est pour ca qu'on peux bouger les lignes de la liste\n\nOn peux appyer sur les fleches haut/bas pour monter/decendre une ligne\nOn peux appuyer sur Page up/Page down pour aller de 10 en 10\nOn peux appyer sur suppr pour supprimer une ligne");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButtonRenameSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameSupprActionPerformed
        java.awt.event.KeyEvent ke = new java.awt.event.KeyEvent(this, 0, 0, 0, KeyEvent.VK_DELETE, 's');
        jListRenameListKeyPressed(ke);
    }//GEN-LAST:event_jButtonRenameSupprActionPerformed

    private void jButtonRenameDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameDownActionPerformed
        java.awt.event.KeyEvent ke = new java.awt.event.KeyEvent(this, 0, 0, 0, KeyEvent.VK_DOWN, 'd');
        jListRenameListKeyPressed(ke);
    }//GEN-LAST:event_jButtonRenameDownActionPerformed

    private void jButtonRenameUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameUpActionPerformed
        java.awt.event.KeyEvent ke = new java.awt.event.KeyEvent(this, 0, 0, 0, KeyEvent.VK_UP, 'u');
        jListRenameListKeyPressed(ke);
    }//GEN-LAST:event_jButtonRenameUpActionPerformed

    private void jButtonConvertirRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirRenameActionPerformed
        DefaultListModel<String> model = (DefaultListModel<String>) jListRenameList.getModel();
        if (model == null || model.size() <= 0) {
            return;
        }
        int len = model.size();
        int j = -1;
        while (len > 0) {
            len /= 10;
            j++;
        }
        for (int i = 0; i < model.size(); i++) {
            if (i == 10) {
                j--;
            }
            if (i == 100) {
                j--;
            }
            if (i == 1000) {
                j--;
            }
            String nb0 = "";
            for (int x = j; x > 0; x--) {
                nb0 += "0";
            }
            String name = model.get(i);
            int pos = name.lastIndexOf('.');
            String extention = name.substring(pos);
            String imgName = nb0 + i + extention;
            File originFile = new File(folder, name);
            File newFile = new File(folder, imgName);
            originFile.renameTo(newFile);
        }
        jLabelRenameNbImage1.setText("Nombres d'images: " + model.getSize() + "/" + model.getSize());
    }//GEN-LAST:event_jButtonConvertirRenameActionPerformed

    private void jListRenameListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListRenameListKeyPressed
        if (!resetList || jListRenameList.getModel().getSize() <= 0) {
            return;
        }
        DefaultListModel<String> model = (DefaultListModel<String>) jListRenameList.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            if (jListRenameList.getSelectedIndex() == 0) {
                return;
            }
            String tmp = model.getElementAt(jListRenameList.getSelectedIndex() - 1);
            model.setElementAt(jListRenameList.getSelectedValue(), jListRenameList.getSelectedIndex() - 1);
            model.setElementAt(tmp, jListRenameList.getSelectedIndex());
            jListRenameList.setSelectedIndex(jListRenameList.getSelectedIndex() - 1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            if (jListRenameList.getSelectedIndex() == (model.getSize() - 1)) {
                return;
            }
            String tmp = model.getElementAt(jListRenameList.getSelectedIndex() + 1);
            model.setElementAt(jListRenameList.getSelectedValue(), jListRenameList.getSelectedIndex() + 1);
            model.setElementAt(tmp, jListRenameList.getSelectedIndex());
            jListRenameList.setSelectedIndex(jListRenameList.getSelectedIndex() + 1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            int minPlace = 0;
            if (jListRenameList.getSelectedIndex() - 10 >= 0) {
                minPlace = jListRenameList.getSelectedIndex() - 10;
            }
            model.add(minPlace, jListRenameList.getSelectedValue());
            model.remove(jListRenameList.getSelectedIndex());
            jListRenameList.setSelectedIndex(minPlace);
        }
        if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            int maxPlace = model.getSize() - 1;
            if (jListRenameList.getSelectedIndex() + 10 <= maxPlace) {
                maxPlace = jListRenameList.getSelectedIndex() + 10;
            }
            model.add(maxPlace, jListRenameList.getSelectedValue());
            model.remove(jListRenameList.getSelectedIndex());
            jListRenameList.setSelectedIndex(maxPlace);
        }
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if ((model.getSize() - 1) <= 0) {
                return;
            }
            int res = jListRenameList.getSelectedIndex() - 1;
            if (res < 0) {
                res = 0;
            }
            model.remove(jListRenameList.getSelectedIndex());
            jListRenameList.setSelectedIndex(res);
        }
    }//GEN-LAST:event_jListRenameListKeyPressed

    private void jButtonConvertirResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirResizeActionPerformed
        File files[] = getFiles(folder, ".jpg");
        new File(folder, "resize").mkdirs();
        int i = 0;
        for (File file : files) {
            try {
                i++;
                magick.launchResize(file, jTextFieldResizeText.getText());
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jLabel1ConvertNbImage.setText("Nombres d'images: " + i + "/" + files.length);
    }//GEN-LAST:event_jButtonConvertirResizeActionPerformed

    private void jLabelResizenfoURL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResizenfoURL1MouseClicked
        String url = "https://imagemagick.org/script/command-line-processing.php#geometry";
        openURL(url);
    }//GEN-LAST:event_jLabelResizenfoURL1MouseClicked

    private void jButtonConvertireConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertireConvertActionPerformed
        if (!jTextFieldConvertExt.getText().startsWith(".")) {
            jTextFieldConvertExt.setText("." + jTextFieldConvertExt.getText().trim());
        }
        File files[] = getFiles(folder, jTextFieldConvertExt.getText());
        new File(folder, "convert").mkdirs();
        int i = 0;
        for (File file : files) {
            try {
                i++;
                magick.launchConvertInm(file, ".jpg");
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jLabelConvertNbImg.setText("Nombres d'images: " + i + "/" + files.length);
    }//GEN-LAST:event_jButtonConvertireConvertActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        JOptionPane.showMessageDialog(this, "La sortie serra toujours en .jpg");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButtonConvertirRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirRotateActionPerformed
        new File(folder, "rotate").mkdirs();
        File files[] = getFiles(folder, ".jpg");
        int i = 0;
        for (File file : files) {
            i++;
            try {
                magick.laumchRotateMagik(file, jTextFieldRotate.getText());
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jLabel1RotateNbImg.setText("Nombres d'images: " + i + "/" + files.length);
    }//GEN-LAST:event_jButtonConvertirRotateActionPerformed

    private void jLabelRotateURL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRotateURL1MouseClicked
        JOptionPane.showMessageDialog(this, "Mettre (en degrés) la rotation.\nPeux etre négatif\n\nExemple: 90 ou -90");
    }//GEN-LAST:event_jLabelRotateURL1MouseClicked

    private void jLabelImg2StendardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImg2StendardMouseClicked
        JOptionPane.showMessageDialog(this, "Si l'un des nom d'une image contient \"paysage\" (exemple: 01-paysage.jpg) elle serra au format paysage dans le rendu du PDF final");
    }//GEN-LAST:event_jLabelImg2StendardMouseClicked

    private void jLabelImg2PdfOriginalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImg2PdfOriginalMouseClicked
        JOptionPane.showMessageDialog(this, "Mets la taille original des images dans le PDF (faites un resize avant !)\nPratique quand les formats ne sont pas standards\nSi l'un des nom d'une image contient \"paysage\" (exemple: 01-paysage.jpg) elle serra au format paysage dans le rendu du PDF final");
    }//GEN-LAST:event_jLabelImg2PdfOriginalMouseClicked

    private void jLabelImg2PdfBDBelgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImg2PdfBDBelgeMouseClicked
        JOptionPane.showMessageDialog(this, "la taille proposé de base (936x1248) c'est la taille 24cmx32cm soit le format d'une BD (belge)\nCela permet de forcer une taille si l'on ne veux pas de la taille original\nSi l'un des nom d'une image contient \"paysage\" (exemple: 01-paysage.jpg) elle serra au format paysage dans le rendu du PDF final", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelImg2PdfBDBelgeMouseClicked

    private void jButtonConvertImg2PdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertImg2PdfActionPerformed
        File files[] = getFiles(folder, ".jpg");
        PageSize pg = null;
        try {
            if (jRadioButtonOriginal.isSelected()) {
                Image image = new Image(ImageDataFactory.create(files[0].getAbsolutePath()));
                pg = new PageSize(image.getImageWidth() / 4, image.getImageHeight() / 4);
            } else if (jRadioButtonStendard.isSelected()) {
                String resStr = jComboBoxImg2PdfPageSize.getSelectedItem().toString();
                Field f = PageSize.class.getField(resStr);
                pg = (PageSize) f.get(null);
            } else {
                pg = new PageSize(Float.parseFloat(jFormattedTextFieldImg2PdfWidth.getText()), Float.parseFloat(jFormattedTextFieldImg2PdfHeight.getText()));
            }
            magick.launchImg2Pdf(files, pg);
            jLabelImg2PDFNbImg1.setText("Nombres d'images: " + files.length);
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConvertImg2PdfActionPerformed

    private void jLabelCropInfosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCropInfosListMouseClicked
        JOptionPane.showMessageDialog(this, "Maintenir shift pour selectionner plusieurs lignes");
    }//GEN-LAST:event_jLabelCropInfosListMouseClicked

    private void jButtonCropToIncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCropToIncludeActionPerformed
        DefaultListModel<String> modelGarde = (DefaultListModel<String>) jListCropAGarder.getModel();
        DefaultListModel<String> modelExclude = (DefaultListModel<String>) jListCropAExclure.getModel();
        int indices[] = jListCropAExclure.getSelectedIndices();
        for (int i = 0; i < indices.length; i++) {
            String value = modelExclude.get(indices[i]);
            modelGarde.addElement(value);
        }
        for (int i = (indices.length - 1); i > -1; i--) {
            modelExclude.removeElementAt(indices[i]);
        }
    }//GEN-LAST:event_jButtonCropToIncludeActionPerformed

    private void jButtonCropToExcludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCropToExcludeActionPerformed
        DefaultListModel<String> modelGarde = (DefaultListModel<String>) jListCropAGarder.getModel();
        DefaultListModel<String> modelExclude = (DefaultListModel<String>) jListCropAExclure.getModel();
        int indices[] = jListCropAGarder.getSelectedIndices();
        for (int i = 0; i < indices.length; i++) {
            String value = modelGarde.get(indices[i]);
            modelExclude.addElement(value);
        }
        for (int i = (indices.length - 1); i > -1; i--) {
            modelGarde.removeElementAt(indices[i]);
        }
    }//GEN-LAST:event_jButtonCropToExcludeActionPerformed

    private void jButtonCropListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCropListerActionPerformed
        File files[] = getFiles(folder, null);
        DefaultListModel<String> model = new DefaultListModel<>();
        for (File file : files) {
            model.addElement(file.getName());
        }
        jListCropAGarder.setModel(model);
        jListCropAExclure.setModel(new DefaultListModel<>());
        if (model.size() > 0) {
            jButtonConvertCrop.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonCropListerActionPerformed

    private void jLabelCropInfosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCropInfosMouseClicked
        JOptionPane.showMessageDialog(this, "En Mode Auto, ca coupe au milieu de l'image.\nSinon il faut mettre une largeure x hauteur (voir \"info sur le templates (geometry) \")\nIl vaut mieux laisser en Auto !", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelCropInfosMouseClicked

    private void jLabelCropinfoGeometryURLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCropinfoGeometryURLMouseClicked
        String url = "https://imagemagick.org/script/command-line-processing.php#geometry";
        openURL(url);
    }//GEN-LAST:event_jLabelCropinfoGeometryURLMouseClicked

    private void jButtonConvertCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertCropActionPerformed
        new File(folder, "crop").mkdirs();
        DefaultListModel<String> model = (DefaultListModel<String>) jListCropAGarder.getModel();
        boolean auto1 = jTextFieldCrop1.getText().contains("Auto");
        boolean auto2 = jTextFieldCrop2.getText().contains("Auto");
        String crop1 = "";
        String crop2 = "";
        Iterator<String> it = model.elements().asIterator();
        int i = 0;
        while (it.hasNext()) {
            File file = new File(folder, it.next());
            try {
                BufferedImage img = ImageIO.read(file);

                int h = img.getHeight();
                int w = img.getWidth();
                if (auto1) {
                    crop1 = w / 2 + "x" + h + "-0-0";
                } else {
                    crop1 = jTextFieldCrop1.getText();
                }
                if (auto2) {
                    crop2 = w / 2 + "x" + h + "+" + w / 2 + "-0";
                } else {
                    crop2 = jTextFieldCrop2.getText();
                }

                magick.laumchCropMagik(file, crop1, 1);
                magick.laumchCropMagik(file, crop2, 2);

                i += 2;
                jLabelCropNbImg.setText("Nombres d'images: " + i + "/" + (model.size() * 2));
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        DefaultListModel<String> modelExclude = (DefaultListModel<String>) jListCropAExclure.getModel();
        Iterator<String> itE = modelExclude.elements().asIterator();
        while (itE.hasNext()) {
            String fn = itE.next();
            File file = new File(folder, fn);
            File newFile = new File(folder, "crop/"+fn);
            try {
                FileUtils.copyFile(file, newFile);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonConvertCropActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        JOptionPane.showMessageDialog(this, "Plus la densité est grande plus la taille du fichier serra grand et lourd.\n\n300 est un tres bon compromis entre qualité / poids / taille", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButtonConvertPdf2ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertPdf2ImgActionPerformed
        File pdfs[] = getFiles(folder, ".pdf");
        if (pdfs.length == 0) {
            JOptionPane.showMessageDialog(this, "Pas de pdf trouver dans le repertoire choisi", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        File pdf = pdfs[0];

        try {
            magick.launchPdf2Img(pdf, jFormattedTextFieldPdf2Img.getText());
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        moveFileToFolder(pdf, "originals");
        File jpgs[] = getFiles(folder, ".jpg");
        jLabelPdf2imgNbImg.setText("Nombres d'images: " + jpgs.length);
    }//GEN-LAST:event_jButtonConvertPdf2ImgActionPerformed

    private boolean resetList = false;

    private void openURL(String url) {
        Desktop desktop = java.awt.Desktop.getDesktop();
        try {
            desktop.browse(new URI(url));
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private File[] getFiles(File folder, String ext) {
        File files[] = null;
        if (ext != null) {
            files = folder.listFiles((File pathname) -> pathname.getName().endsWith(ext));
        } else {
            files = folder.listFiles((File pathname) -> pathname.isFile());
        }
        Arrays.sort(files, Comparator.comparing(File::getName));
        return files;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupImg2Pdf;
    private javax.swing.JButton jButtonConvertCrop;
    private javax.swing.JButton jButtonConvertImg2Pdf;
    private javax.swing.JButton jButtonConvertPdf2Img;
    private javax.swing.JButton jButtonConvertirRename;
    private javax.swing.JButton jButtonConvertirResize;
    private javax.swing.JButton jButtonConvertirRotate;
    private javax.swing.JButton jButtonConvertireConvert;
    private javax.swing.JButton jButtonCropLister;
    private javax.swing.JButton jButtonCropToExclude;
    private javax.swing.JButton jButtonCropToInclude;
    private javax.swing.JButton jButtonOpenFolder;
    private javax.swing.JButton jButtonRenameDown;
    private javax.swing.JButton jButtonRenamePgDown;
    private javax.swing.JButton jButtonRenamePgUp;
    private javax.swing.JButton jButtonRenameReset;
    private javax.swing.JButton jButtonRenameSuppr;
    private javax.swing.JButton jButtonRenameUp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBoxImg2PdfPageSize;
    private javax.swing.JFormattedTextField jFormattedTextFieldImg2PdfHeight;
    private javax.swing.JFormattedTextField jFormattedTextFieldImg2PdfWidth;
    private javax.swing.JFormattedTextField jFormattedTextFieldPdf2Img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel1ConvertNbImage;
    private javax.swing.JLabel jLabel1RotateNbImg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelConvertNbImg;
    private javax.swing.JLabel jLabelCropInfos;
    private javax.swing.JLabel jLabelCropInfosList;
    private javax.swing.JLabel jLabelCropNbImg;
    private javax.swing.JLabel jLabelCropinfoGeometryURL;
    private javax.swing.JLabel jLabelFolder;
    private javax.swing.JLabel jLabelImg2PDFNbImg1;
    private javax.swing.JLabel jLabelImg2PdfBDBelge;
    private javax.swing.JLabel jLabelImg2PdfOriginal;
    private javax.swing.JLabel jLabelImg2Stendard;
    private javax.swing.JLabel jLabelNbImageCrop;
    private javax.swing.JLabel jLabelPdf2imgNbImg;
    private javax.swing.JLabel jLabelRenameNbImage1;
    private javax.swing.JLabel jLabelResizenfoURL1;
    private javax.swing.JLabel jLabelRotateURL1;
    private javax.swing.JList<String> jListCropAExclure;
    private javax.swing.JList<String> jListCropAGarder;
    private javax.swing.JList<String> jListRenameList;
    private javax.swing.JPanel jPanelConvert;
    private javax.swing.JPanel jPanelCrop;
    private javax.swing.JPanel jPanelPdf2Imag;
    private javax.swing.JPanel jPanelRename;
    private javax.swing.JPanel jPanelResize;
    private javax.swing.JPanel jPanelRotate;
    private javax.swing.JPanel jPanelimg2Pdf;
    private javax.swing.JRadioButton jRadioButtonBdBelge;
    private javax.swing.JRadioButton jRadioButtonOriginal;
    private javax.swing.JRadioButton jRadioButtonStendard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldConvertExt;
    private javax.swing.JTextField jTextFieldCrop1;
    private javax.swing.JTextField jTextFieldCrop2;
    private javax.swing.JTextField jTextFieldResizeText;
    private javax.swing.JTextField jTextFieldRotate;
    // End of variables declaration//GEN-END:variables
}
